Repository ysJun0608/ssg-team2-sellpick, pull requests merged in 2024-02, with the labels that each got.

#7 CREATE : Initial Package
  src/DBIO/ObjectDBIO.java
  src/TODO
  src/delivery/dao/WaybillDao.java
  src/delivery/domain/DeliveryCmp.java
  src/delivery/domain/Waybill.java
  src/delivery/service/WaybillService.java
  src/delivery/service/impl/WaybillServiceImpl.java
  src/inventory/dao/DeadlineDao.java
  src/inventory/dao/InventoryDao.java
  src/inventory/dao/WarehouseDao.java
  src/inventory/dao/WarehouseInsertRelease.java
  src/inventory/domain/Deadline.java
  src/inventory/domain/Inventory.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseInsertRelease.java
  src/inventory/service/DeadlineService.java
  src/inventory/service/InventoryService.java
  src/inventory/service/WarehouseInsertReleaseService.java
  src/inventory/service/WarehouseService.java
  src/inventory/service/impl/DeadlineServiceImpl.java
  src/inventory/service/impl/InventoryServiceImpl.java
  src/inventory/service/impl/WarehouseInsertReleaseServiceImpl.java
  src/inventory/service/impl/WarehouseServiceImpl.java
  src/main/MainMenu.java
  src/mgtOrders/dao/MgtOrderDao.java
  src/mgtOrders/domain/MgtOrder.java
  src/mgtOrders/service/MgtOrdersService.java
  src/mgtOrders/service/impl/MgtOrdersServiceImpl.java
  src/person/dao/BusinessOwnerDao.java
  src/person/dao/CustomerDao.java
  src/person/domain/BusinessOwner.java
  src/person/domain/Customer.java
  src/person/service/BusinessOwnerService.java
  src/person/service/CustomerService.java
  src/person/service/impl/BusinessOwnerServiceImpl.java
  src/person/service/impl/CustomerServiceImpl.java
  src/product/dao/BrandDao.java
  src/product/dao/ProductsDao.java
  src/product/domain/Brand.java
  src/product/domain/Products.java
  src/product/service/BrandService.java
  src/product/service/ProductsService.java
  src/product/service/impl/BrandServiceImpl.java
  src/product/service/impl/ProductsServiceImpl.java
  src/smOrders/dao/SMOrdersDao.java
  src/smOrders/dao/ShoppingMallDao.java
  src/smOrders/domain/SMOrders.java
  src/smOrders/domain/ShoppingMall.java
  src/smOrders/service/SMOrdersService.java
  src/smOrders/service/ShoppingMallService.java
  src/smOrders/service/impl/SMOrderServiceImpl.java
  src/smOrders/service/impl/ShoppingMallServiceImpl.java
Labels: enhancement

#9 CREATE : DDL
  db/init/create_database_and_tables.sql
Labels: documentation, enhancement

#13 REFACTOR : domain 클래스 필드 변경 및 DDL 수정
  db/init/create_database_and_tables.sql
  src/delivery/domain/DeliveryCmp.java
  src/delivery/domain/Waybill.java
  src/inventory/dao/InventoryDao.java
  src/inventory/domain/Deadline.java
  src/inventory/domain/Inventory.java
  src/inventory/domain/Settlement.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseInsertRelease.java
  src/mgtOrders/domain/MgtOrder.java
  src/person/domain/Customer.java
  src/product/domain/Brand.java
  src/product/domain/Products.java
  src/smOrders/domain/SMOrders.java
  src/smOrders/domain/ShoppingMall.java
Labels: enhancement

#16 CREATE : 더미 데이터 및 새로운 테이블 생성
  db/init/create_database_and_tables.sql
  db/init/create_dummy_data.sql
  src/inventory/dao/WhInOutSettlementRelationshipDao.java
  src/inventory/domain/WhInOutSettlementRelationship.java
Labels: enhancement

#17 FIX : PK에 AutoIncrement 되지 않아 변경
  db/init/create_database_and_tables.sql
Labels: bug

#20 REFACTOR : delete customerId column
  db/init/create_database_and_tables.sql
  src/delivery/domain/Waybill.java
Labels: bug

#23 REFACTOR : ERD 수정으로 인해 DDL 및 클래스 수정
  db/init/create_database_and_tables.sql
  src/delivery/domain/DeliveryCmp.java
  src/delivery/domain/Waybill.java
  src/inventory/domain/Inventory.java
  src/inventory/domain/Settlement.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseInsertRelease.java
  src/inventory/domain/WarehouseSection.java
  src/inventory/domain/WhInOutSettlementRelationship.java
  src/inventory/domain/WhSmRelationShip.java
  src/inventory/enums/WhInOutType.java
  src/inventory/enums/WhType.java
  src/mgtOrders/domain/MgtOrder.java
  src/mgtOrders/domain/MgtOrders.java
  src/mgtOrders/domain/MgtOrdersProductsRelationship.java
  src/mgtOrders/enums/MgtOrdersStatus.java
  src/person/domain/BusinessOwner.java
  src/product/domain/Brand.java
  src/product/domain/Products.java
  src/smOrders/domain/SMOrders.java
  src/smOrders/domain/ShoppingMall.java
Labels: bug, enhancement

#24 STYLE : DATA Annotaion
  src/delivery/domain/DeliveryCmp.java
  src/delivery/domain/Waybill.java
  src/inventory/domain/Inventory.java
  src/inventory/domain/Settlement.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseInsertRelease.java
  src/inventory/domain/WarehouseSection.java
  src/inventory/domain/WhInOutSettlementRelationship.java
  src/inventory/domain/WhSmRelationShip.java
  src/mgtOrders/domain/MgtOrders.java
  src/mgtOrders/domain/MgtOrdersProductsRelationship.java
  src/person/domain/BusinessOwner.java
  src/person/domain/Customer.java
  src/product/domain/Brand.java
  src/product/domain/Products.java
  src/smOrders/domain/SMOrders.java
Labels: enhancement

#26 REFACTOR : DDL 또 다시 변경
  db/init/create_database_and_tables.sql
  src/inventory/dao/WarehouseInsertReleaseDao.java
  src/inventory/enums/WhInOutType.java
  src/inventory/enums/WhSectionType.java
  src/inventory/enums/WhType.java
  src/mgtOrders/domain/MgtOrders.java
  src/mgtOrders/enums/MgtOrdersStatus.java
  src/smOrders/domain/SMOrders.java
  src/smOrders/enums/SellerSendStatus.java
Labels: enhancement

#28 부탁드립니다
  db/init/create_database_and_tables.sql
  src/DBIO/ObjectDBIO.java
  src/README.md
  src/delivery/dao/DeliverCmpDao.java
  src/delivery/service/DeliveryCmpService.java
  src/delivery/service/impl/DeliveryCmpServiceImpl.java
  src/inventory/dao/DeadlineDao.java
  src/inventory/dao/SettlementDao.java
  src/inventory/dao/WarehouseDao.java
  src/inventory/dao/WarehouseInsertReleaseDao.java
  src/inventory/dao/WarehouseSectionDao.java
  src/inventory/dao/WhSmRelationshipDao.java
  src/inventory/domain/InsertReleaseType.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseSection.java
  src/inventory/domain/WarehouseType.java
  src/inventory/domain/WhSmRelationship.java
  src/inventory/service/DeadlineService.java
  src/inventory/service/SettlementService.java
  src/inventory/service/WarehouseInsertReleaseService.java
  src/inventory/service/WarehouseSectionService.java
  src/inventory/service/WarehouseService.java
  src/inventory/service/WhSmRelationShipService.java
  src/inventory/service/impl/DeadlineServiceImpl.java
  src/inventory/service/impl/WarehouseInsertReleaseServiceImpl.java
  src/inventory/service/impl/WarehouseSectionServiceImpl.java
  src/inventory/service/impl/WarehouseServiceImpl.java
  src/inventory/service/impl/WhSmRelationShipServiceImpl.java
  src/main/MainMenu.java
  src/mgtOrders/domain/MgtOrderProductsRelationship.java
  src/smOrders/dao/ShoppingMallDao.java
  src/smOrders/domain/ShoppingMall.java
  src/smOrders/service/ShoppingMallService.java
  src/smOrders/service/impl/SMOrderServiceImpl.java
  src/smOrders/service/impl/ShoppingMallServiceImpl.java
Labels: enhancement

#29 클래명 변경 후 main으로 다시 머지
  src/inventory/dao/WhSmRelationshipDao.java
  src/inventory/domain/WhSmRelationShip.java
  src/inventory/domain/WhSmRelationship.java
  src/inventory/service/WhSmRelationShipService.java
  src/inventory/service/impl/WarehouseServiceImpl.java
  src/inventory/service/impl/WhSmRelationShipServiceImpl.java
Labels: bug, documentation

#32 Lee da hye MERGE
  README.md
  db/init/create_database_and_tables.sql
  src/DBIO/ObjectDBIO.java
  src/delivery/dao/DeliveryCmpDao.java
  src/delivery/dao/WaybillDao.java
  src/delivery/domain/Waybill.java
  src/delivery/dto/SelectWaybillOutPut.java
  src/delivery/service/WaybillService.java
  src/delivery/service/impl/DeliveryCmpServiceImpl.java
  src/delivery/service/impl/WaybillServiceImpl.java
  src/inventory/dao/WhSmRelationshipDao.java
  src/inventory/domain/WhSmRelationship.java
Labels: bug, enhancement

#35 Moon ji hwan MERGE
  README.md
  db/init/create_database_and_tables.sql
  src/DBIO/ObjectDBIO.java
  src/README.md
  src/inventory/dao/WarehouseDao.java
  src/inventory/dao/WarehouseInsertReleaseDao.java
  src/inventory/dao/WhSmRelationshipDao.java
  src/inventory/domain/InsertReleaseType.java
  src/inventory/domain/Warehouse.java
  src/inventory/domain/WarehouseType.java
  src/inventory/service/WhSmRelationShipService.java
  src/inventory/service/WhSmRelationshipService.java
  src/inventory/service/impl/WarehouseServiceImpl.java
  src/inventory/service/impl/WhSmRelationShipServiceImpl.java
  src/inventory/service/impl/WhSmRelationshipServiceImpl.java
  src/main/MainMenu.java
  src/product/dao/BrandDao.java
  src/product/dao/ProductsDao.java
  src/product/domain/Products.java
  src/product/enums/ProductsStatus.java
  src/product/service/BrandService.java
  src/product/service/ProductsService.java
  src/product/service/impl/BrandServiceImpl.java
  src/product/service/impl/ProductsServiceImpl.java
  src/smOrders/service/impl/ShoppingMallServiceImpl.java
Labels: enhancement

#36 merge전 푸시
  README.md
  src/DBIO/ObjectDBIO.java
  src/inventory/dao/WarehouseInsertReleaseDao.java
  src/mgtOrders/dao/MgtOrderDao.java
  src/mgtOrders/domain/MgtOrderProductsRelationship.java
  src/mgtOrders/domain/MgtOrders.java
  src/mgtOrders/service/MgtOrdersService.java
  src/mgtOrders/service/impl/MgtOrdersServiceImpl.java
Labels: enhancement

#38 Lee do yeop 제발 .... merge전 마지막?
  README.md
  src/person/domain/BusinessOwner.java
  src/person/domain/Customer.java
  src/smOrders/dao/SMOrdersDao.java
  src/smOrders/domain/SellerSendStatus.java
  src/smOrders/domain/smOrders.java
  src/smOrders/dto/SmOrdersOutput.java
  src/smOrders/service/SMOrdersService.java
  src/smOrders/service/SmOrdersService.java
  src/smOrders/service/impl/SMOrderServiceImpl.java
  src/smOrders/service/impl/SmOrderServiceImpl.java
  src/smOrders/smOrdersMain.java
Labels: bug, enhancement

#39 merge후 수리 - 중복되는 클래스 제거
  src/smOrders/dao/SMOrdersDao.java
  src/smOrders/domain/SellerSendStatus.java
  src/smOrders/domain/smOrders.java
  src/smOrders/service/impl/SmOrderServiceImpl.java
Labels: bug

#41 CREATE : 1차 프로젝트 결과
  db/init/create_database_and_tables.sql
  src/DBIO/ObjectDBIO.java
  src/delivery/dao/DeliveryCmpDao.java
  src/delivery/dao/WaybillDao.java
  src/delivery/deliveryMain.java
  src/delivery/dto/SelectListWaybillOutput.java
  src/delivery/service/WaybillService.java
  src/delivery/service/impl/WaybillServiceImpl.java
  src/inventory/InventoryMain.java
  src/inventory/SettlementMain.java
  src/inventory/WarehouseMain.java
  src/inventory/dao/InventoryDao.java
  src/inventory/dao/SettlementDao.java
  src/inventory/dao/WarehouseDao.java
  src/inventory/dao/WarehouseInsertReleaseDao.java
  src/inventory/dao/WarehouseSectionDao.java
  src/inventory/dao/WhSmRelationshipDao.java
  src/inventory/dto/InventoryOutput.java
  src/inventory/service/InventoryService.java
  src/inventory/service/SettlementService.java
  src/inventory/service/WarehouseInsertReleaseService.java
  src/inventory/service/WarehouseSectionService.java
  src/inventory/service/WarehouseService.java
  src/inventory/service/impl/DeadlineServiceImpl.java
  src/inventory/service/impl/InventoryServiceImpl.java
  src/inventory/service/impl/SettlementServiceImpl.java
  src/inventory/service/impl/WarehouseInsertReleaseServiceImpl.java
  src/inventory/service/impl/WarehouseSectionServiceImpl.java
  src/inventory/service/impl/WarehouseServiceImpl.java
  src/main/MainMenu.java
  src/main/WmsTraining.java
  src/mgtOrders/MgtOrdersMain.java
  src/mgtOrders/dao/MgtOrderDao.java
  src/mgtOrders/domain/MgtOrderProductsRelationship.java
  src/mgtOrders/domain/MgtOrders.java
  src/mgtOrders/domain/MgtOrdersProductsRelationship.java
  src/mgtOrders/domain/WarehouseInsertRelease.java
  src/mgtOrders/service/MgtOrdersService.java
  src/mgtOrders/service/impl/MgtOrdersServiceImpl.java
  src/product/dao/BrandDao.java
  src/product/dao/ProductsDao.java
  src/product/dto/ProductsOutput.java
  src/product/service/impl/ProductsServiceImpl.java
  src/smOrders/SmOrdersMain.java
  src/smOrders/dao/SMOrdersDao.java
  src/smOrders/dto/SmOrdersAllOutput.java
  src/smOrders/service/SmOrdersService.java
  src/smOrders/service/impl/ShoppingMallServiceImpl.java
  src/smOrders/service/impl/SmOrderServiceImpl.java
  src/smOrders/smOrdersMain.java
  test.puml
Labels: enhancement

#42 1차 프로젝트 후 자잘한 수정
  db/init/create_database_and_tables.sql
  src/config/printEndImage/ImageDisplay.java
  src/config/printEndImage/ThankYou.gif
  src/config/printWMSTraing/WmsTraining.java
  src/inventory/service/impl/WarehouseSectionServiceImpl.java
  src/main/MainMenu.java
  src/main/WmsTraining.java
  src/smOrders/dao/SMOrdersDao.java
  src/smOrders/service/impl/SmOrderServiceImpl.java
Labels: documentation
